
# DEBUG
DEBUG = True

# DISPLAY SETTINGS
SCREEN_WIDTH = 800
SCREEN_HEIGHT = 600

class GameSettings:
    # BUBBLE SETTINGS
    NUMBER_OF_BUBBLES = 100
    BUBBLE_MAXH = 180

    # PLAYER SETTINGS
    PLAYER_EXPLOSIONS = 10
    PLAYER_LIVES = 3

    # EXPLOSION SETTINGS
    EXPLOSION_MAX_LIVES = 25
    EXPLOSION_RADIUS = 3
    EXPLOSION_RADIUS_DELTA = 3

