
# DEBUG
DEBUG = False

# DISPLAY SETTINGS
SCREEN_WIDTH = 800
SCREEN_HEIGHT = 600

class InterfaceSettings:
    MOUSEHIGHLIGHTFONTCOLOR = (255, 255, 255)
    FONTCOLOR = (215, 215, 215)
    FONTSTYLE = 'bradleyhanditc'

class GameSettings:
    # BUBBLE SETTINGS
    NUMBER_OF_BUBBLES = 25
    BUBBLE_MAXH = 100

    # PLAYER SETTINGS
    PLAYER_EXPLOSIONS = 25
    PLAYER_LIVES = 3

    # EXPLOSION SETTINGS
    EXPLOSION_MAX_LIVES = 30
    EXPLOSION_RADIUS = 5
    EXPLOSION_RADIUS_DELTA = 5

    SMALLEXPLOSIONCOST = 1
    LARGEEXPLOSIONCOST = 5

