
# DEBUG
DEBUG = True

# VERSION
VERSION = 0.001

# BUBBLE SETTINGS
NUMBER_OF_BUBBLES = 10
BUBBLE_MAXH = 200
BUBBLEPOPDELAY = 500
BUBBLE_MAXDELTA = 300

# PLAYER SETTINGS
PLAYER_EXPLOSIONS = 10
PLAYER_LIVES = 3

# EXPLOSION SETTINGS
EXPLOSION_MAX_LIVES = 25
EXPLOSION_RADIUS = 10 
EXPLOSION_RADIUS_DELTA = 5

SMALLEXPLOSIONCOST = 1
LARGEEXPLOSIONCOST = 2

class InterfaceSettings:
    # DISPLAY SETTINGS
    SCREEN_WIDTH = 0 # use fullscreen resolution
    SCREEN_HEIGHT = 0
    BACKGROUND_COLOR = (0, 0, 0)

    # FONT SETTINGS
    MOUSEHIGHLIGHTFONTCOLOR = (255, 255, 255)
    FONTTITLECOLOR = (255, 255, 255)
    FONTCOLOR = (205, 205, 205)
    FONTSTYLE = 'resources/GFSCUS1D.ttf'

    # BUBBLES
    BUBBLECOLORS = ['blue', 'cyan', 'green', 'orange', 'pink']


class GameSettings:
    # i dont like dis
    @staticmethod
    def init():
        # BUBBLE SETTINGS
        GameSettings.NUMBER_OF_BUBBLES = NUMBER_OF_BUBBLES
        GameSettings.BUBBLE_MAXH = BUBBLE_MAXH
        GameSettings.BUBBLEPOPDELAY = BUBBLEPOPDELAY
        GameSettings.BUBBLE_MAXDELTA = BUBBLE_MAXDELTA

        # PLAYER SETTINGS
        GameSettings.PLAYER_EXPLOSIONS = PLAYER_EXPLOSIONS
        GameSettings.PLAYER_LIVES = PLAYER_LIVES

        # EXPLOSION SETTINGS
        GameSettings.EXPLOSION_MAX_LIVES = EXPLOSION_MAX_LIVES
        GameSettings.EXPLOSION_RADIUS = EXPLOSION_RADIUS
        GameSettings.EXPLOSION_RADIUS_DELTA = EXPLOSION_RADIUS_DELTA

        GameSettings.SMALLEXPLOSIONCOST = SMALLEXPLOSIONCOST
        GameSettings.LARGEEXPLOSIONCOST = LARGEEXPLOSIONCOST
